DEFAULT_SPEAKER_ID = 2
DEFAULT_SPEED_SCALE = 1.0
DEFAULT_PITCH_SCALE = -0.08
DEFAULT_INTONATION_SCALE = 1.25

__all__ = [
    "DEFAULT_SPEAKER_ID",
    "DEFAULT_SPEED_SCALE",
    "DEFAULT_PITCH_SCALE",
    "DEFAULT_INTONATION_SCALE",
]
